// Generated by scripts/bump-version.mjs — do not hand-edit. Run
// `pnpm bump <patch|minor|major>` instead, which keeps this, every
// package.json in the workspace, and the MQL5 EA's version string in sync.
export const APP_VERSION = "0.1.0";
