#!/usr/bin/env node
// Unified version bump: one semver string across every package.json in the
// workspace, the bridge's compiled-in version constant, and the MQL5 EA's
// own version properties — see project memory
// project_xau_trader_web_platform's self-update section for why (these had
// drifted independently before this script existed: npm packages sat at
// 0.1.0 while the EA reported 1.11).
//
// Usage: node scripts/bump-version.mjs <patch|minor|major>
//    or: pnpm bump <patch|minor|major>
//
// Deliberately does not commit, tag, or push on its own — review the diff
// first (a bump also touches the compiled EA's displayed version, worth a
// look before committing), then commit/tag/push as a normal, explicit step.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const bumpType = process.argv[2];
if (!["patch", "minor", "major"].includes(bumpType)) {
  console.error("Usage: node scripts/bump-version.mjs <patch|minor|major>");
  process.exit(1);
}

const rootPkgPath = path.join(ROOT, "package.json");
const rootPkg = JSON.parse(readFileSync(rootPkgPath, "utf8"));
const [maj, min, pat] = rootPkg.version.split(".").map(Number);
const next =
  bumpType === "major" ? `${maj + 1}.0.0` : bumpType === "minor" ? `${maj}.${min + 1}.0` : `${maj}.${min}.${pat + 1}`;

// Validated before any file is touched — MetaEditor's compiler rejects
// "0.x" outright for #property version ("incompatible with MQL5 Market"),
// confirmed empirically by actually compiling after a bump (0.2, 0.20, and
// 0.2.0 all warned; 1.20 didn't — it's specifically major=0 that's
// invalid, not digit count or padding). A bump landing on major 0 can
// never produce a clean EA compile, so fail loudly up front rather than
// leaving package.json/version.ts bumped while the EA silently isn't.
const [nextMajCheck] = next.split(".");
if (Number(nextMajCheck) < 1) {
  console.error(
    `\nERROR: version ${next} has major 0 — MQL5's #property version rejects "0.x" outright. ` +
      `Use a version with major >= 1 (e.g. "pnpm bump major" from 0.x.x to reach 1.0.0) before bumping.`,
  );
  process.exit(1);
}

console.log(`Bumping version: ${rootPkg.version} -> ${next}`);

// Every npm package in the workspace shares this one version.
const pkgPaths = ["package.json", "apps/bridge/package.json", "apps/web/package.json", "packages/protocol/package.json"];
for (const rel of pkgPaths) {
  const p = path.join(ROOT, rel);
  const pkg = JSON.parse(readFileSync(p, "utf8"));
  pkg.version = next;
  writeFileSync(p, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`  ${rel}`);
}

// The bridge's own compiled-in version constant — a plain committed file
// rather than a build-time esbuild --define, so it reads the same way in
// dev (pnpm dev:bridge, straight through tsx) and in the packaged binary.
// Read by apps/bridge/src/updateCheck.ts to compare against GitHub
// Releases, and shown in the Settings "Updates" section.
const versionTsPath = path.join(ROOT, "apps/bridge/src/version.ts");
writeFileSync(
  versionTsPath,
  `// Generated by scripts/bump-version.mjs — do not hand-edit. Run\n` +
    `// \`pnpm bump <patch|minor|major>\` instead, which keeps this, every\n` +
    `// package.json in the workspace, and the MQL5 EA's version string in sync.\n` +
    `export const APP_VERSION = "${next}";\n`,
);
console.log(`  apps/bridge/src/version.ts`);

// MQL5 EA — same version, so "the app's version" means one thing across
// the whole system rather than an npm number and a separately drifting EA
// number. One wrinkle: MetaEditor's compiler enforces #property version as
// exactly MAJOR.MINOR, not full semver (warning 68 otherwise — "must be
// xxx.yyy", found by actually compiling, not from docs) — gets the
// truncated two-part form. XAUT_EA_VERSION (a plain string constant, not
// compiler-checked) gets the full version and is what actually reports
// over the wire in the bridge "hello" handshake, so nothing user-visible
// loses patch granularity — only the EA's own Properties-tab display does.
const [nextMaj, nextMin] = next.split(".");
const eaPropertyVersion = `${nextMaj}.${nextMin}`;
const eaPath = path.join(ROOT, "MQL5/Experts/XAU-Trader/XAU_Trader.mq5");
let ea = readFileSync(eaPath, "utf8");
const before = ea;
ea = ea.replace(/#property version\s+"[^"]+"/, `#property version   "${eaPropertyVersion}"`);
ea = ea.replace(/#define XAUT_EA_VERSION "[^"]+"/, `#define XAUT_EA_VERSION "${next}"`);
if (ea === before) {
  console.warn(`  WARNING: no #property version / XAUT_EA_VERSION match found in ${eaPath} — EA version left unchanged`);
} else {
  writeFileSync(eaPath, ea);
  console.log(`  MQL5/Experts/XAU-Trader/XAU_Trader.mq5`);
}

console.log(`\nDone. Next: recompile the EA (0 errors/0 warnings), review the diff, then commit + tag (e.g. "v${next}") + push yourself.`);
